/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as DataRouteImport } from './routes/data'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketsNewRouteImport } from './routes/tickets.new'
import { Route as TicketsKanbanRouteImport } from './routes/tickets.kanban'
import { Route as TicketsTicketIdRouteImport } from './routes/tickets.$ticketId'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as OnboardingLanguageRouteImport } from './routes/onboarding.language'
import { Route as LeadsNewRouteImport } from './routes/leads.new'
import { Route as LeadsKanbanRouteImport } from './routes/leads.kanban'
import { Route as LeadsLeadIdRouteImport } from './routes/leads.$leadId'
import { Route as ClientsNewRouteImport } from './routes/clients.new'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as TicketsTicketIdEditRouteImport } from './routes/tickets.$ticketId.edit'
import { Route as ProjectsProjectIdEditRouteImport } from './routes/projects.$projectId.edit'
import { Route as LeadsLeadIdEditRouteImport } from './routes/leads.$leadId.edit'
import { Route as LeadsLeadIdConvertRouteImport } from './routes/leads.$leadId.convert'
import { Route as ClientsClientIdEditRouteImport } from './routes/clients.$clientId.edit'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsNewRoute = TicketsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TicketsRoute,
} as any)
const TicketsKanbanRoute = TicketsKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => TicketsRoute,
} as any)
const TicketsTicketIdRoute = TicketsTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => TicketsRoute,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const OnboardingLanguageRoute = OnboardingLanguageRouteImport.update({
  id: '/onboarding/language',
  path: '/onboarding/language',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsNewRoute = LeadsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LeadsRoute,
} as any)
const LeadsKanbanRoute = LeadsKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => LeadsRoute,
} as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => LeadsRoute,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ClientsRoute,
} as any)
const TicketsTicketIdEditRoute = TicketsTicketIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TicketsTicketIdRoute,
} as any)
const ProjectsProjectIdEditRoute = ProjectsProjectIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const LeadsLeadIdEditRoute = LeadsLeadIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => LeadsLeadIdRoute,
} as any)
const LeadsLeadIdConvertRoute = LeadsLeadIdConvertRouteImport.update({
  id: '/convert',
  path: '/convert',
  getParentRoute: () => LeadsLeadIdRoute,
} as any)
const ClientsClientIdEditRoute = ClientsClientIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ClientsClientIdRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRoute
  '/leads': typeof LeadsRouteWithChildren
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/search': typeof SearchRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/clients/$clientId': typeof ClientsClientIdRouteWithChildren
  '/clients/new': typeof ClientsNewRoute
  '/leads/$leadId': typeof LeadsLeadIdRouteWithChildren
  '/leads/kanban': typeof LeadsKanbanRoute
  '/leads/new': typeof LeadsNewRoute
  '/onboarding/language': typeof OnboardingLanguageRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRouteWithChildren
  '/tickets/kanban': typeof TicketsKanbanRoute
  '/tickets/new': typeof TicketsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/clients/$clientId/edit': typeof ClientsClientIdEditRoute
  '/leads/$leadId/convert': typeof LeadsLeadIdConvertRoute
  '/leads/$leadId/edit': typeof LeadsLeadIdEditRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/tickets/$ticketId/edit': typeof TicketsTicketIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRoute
  '/leads': typeof LeadsRouteWithChildren
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/search': typeof SearchRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/clients/$clientId': typeof ClientsClientIdRouteWithChildren
  '/clients/new': typeof ClientsNewRoute
  '/leads/$leadId': typeof LeadsLeadIdRouteWithChildren
  '/leads/kanban': typeof LeadsKanbanRoute
  '/leads/new': typeof LeadsNewRoute
  '/onboarding/language': typeof OnboardingLanguageRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRouteWithChildren
  '/tickets/kanban': typeof TicketsKanbanRoute
  '/tickets/new': typeof TicketsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/clients/$clientId/edit': typeof ClientsClientIdEditRoute
  '/leads/$leadId/convert': typeof LeadsLeadIdConvertRoute
  '/leads/$leadId/edit': typeof LeadsLeadIdEditRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/tickets/$ticketId/edit': typeof TicketsTicketIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clients': typeof ClientsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRoute
  '/leads': typeof LeadsRouteWithChildren
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/search': typeof SearchRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/clients/$clientId': typeof ClientsClientIdRouteWithChildren
  '/clients/new': typeof ClientsNewRoute
  '/leads/$leadId': typeof LeadsLeadIdRouteWithChildren
  '/leads/kanban': typeof LeadsKanbanRoute
  '/leads/new': typeof LeadsNewRoute
  '/onboarding/language': typeof OnboardingLanguageRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRouteWithChildren
  '/tickets/kanban': typeof TicketsKanbanRoute
  '/tickets/new': typeof TicketsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/clients/$clientId/edit': typeof ClientsClientIdEditRoute
  '/leads/$leadId/convert': typeof LeadsLeadIdConvertRoute
  '/leads/$leadId/edit': typeof LeadsLeadIdEditRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/tickets/$ticketId/edit': typeof TicketsTicketIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients'
    | '/dashboard'
    | '/data'
    | '/leads'
    | '/login'
    | '/projects'
    | '/search'
    | '/tickets'
    | '/clients/$clientId'
    | '/clients/new'
    | '/leads/$leadId'
    | '/leads/kanban'
    | '/leads/new'
    | '/onboarding/language'
    | '/projects/$projectId'
    | '/projects/new'
    | '/tickets/$ticketId'
    | '/tickets/kanban'
    | '/tickets/new'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/clients/$clientId/edit'
    | '/leads/$leadId/convert'
    | '/leads/$leadId/edit'
    | '/projects/$projectId/edit'
    | '/tickets/$ticketId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/dashboard'
    | '/data'
    | '/leads'
    | '/login'
    | '/projects'
    | '/search'
    | '/tickets'
    | '/clients/$clientId'
    | '/clients/new'
    | '/leads/$leadId'
    | '/leads/kanban'
    | '/leads/new'
    | '/onboarding/language'
    | '/projects/$projectId'
    | '/projects/new'
    | '/tickets/$ticketId'
    | '/tickets/kanban'
    | '/tickets/new'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/clients/$clientId/edit'
    | '/leads/$leadId/convert'
    | '/leads/$leadId/edit'
    | '/projects/$projectId/edit'
    | '/tickets/$ticketId/edit'
  id:
    | '__root__'
    | '/'
    | '/clients'
    | '/dashboard'
    | '/data'
    | '/leads'
    | '/login'
    | '/projects'
    | '/search'
    | '/tickets'
    | '/clients/$clientId'
    | '/clients/new'
    | '/leads/$leadId'
    | '/leads/kanban'
    | '/leads/new'
    | '/onboarding/language'
    | '/projects/$projectId'
    | '/projects/new'
    | '/tickets/$ticketId'
    | '/tickets/kanban'
    | '/tickets/new'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/clients/$clientId/edit'
    | '/leads/$leadId/convert'
    | '/leads/$leadId/edit'
    | '/projects/$projectId/edit'
    | '/tickets/$ticketId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DataRoute: typeof DataRoute
  LeadsRoute: typeof LeadsRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SearchRoute: typeof SearchRoute
  TicketsRoute: typeof TicketsRouteWithChildren
  OnboardingLanguageRoute: typeof OnboardingLanguageRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/new': {
      id: '/tickets/new'
      path: '/new'
      fullPath: '/tickets/new'
      preLoaderRoute: typeof TicketsNewRouteImport
      parentRoute: typeof TicketsRoute
    }
    '/tickets/kanban': {
      id: '/tickets/kanban'
      path: '/kanban'
      fullPath: '/tickets/kanban'
      preLoaderRoute: typeof TicketsKanbanRouteImport
      parentRoute: typeof TicketsRoute
    }
    '/tickets/$ticketId': {
      id: '/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof TicketsTicketIdRouteImport
      parentRoute: typeof TicketsRoute
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/onboarding/language': {
      id: '/onboarding/language'
      path: '/onboarding/language'
      fullPath: '/onboarding/language'
      preLoaderRoute: typeof OnboardingLanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/new': {
      id: '/leads/new'
      path: '/new'
      fullPath: '/leads/new'
      preLoaderRoute: typeof LeadsNewRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/leads/kanban': {
      id: '/leads/kanban'
      path: '/kanban'
      fullPath: '/leads/kanban'
      preLoaderRoute: typeof LeadsKanbanRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/tickets/$ticketId/edit': {
      id: '/tickets/$ticketId/edit'
      path: '/edit'
      fullPath: '/tickets/$ticketId/edit'
      preLoaderRoute: typeof TicketsTicketIdEditRouteImport
      parentRoute: typeof TicketsTicketIdRoute
    }
    '/projects/$projectId/edit': {
      id: '/projects/$projectId/edit'
      path: '/edit'
      fullPath: '/projects/$projectId/edit'
      preLoaderRoute: typeof ProjectsProjectIdEditRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/leads/$leadId/edit': {
      id: '/leads/$leadId/edit'
      path: '/edit'
      fullPath: '/leads/$leadId/edit'
      preLoaderRoute: typeof LeadsLeadIdEditRouteImport
      parentRoute: typeof LeadsLeadIdRoute
    }
    '/leads/$leadId/convert': {
      id: '/leads/$leadId/convert'
      path: '/convert'
      fullPath: '/leads/$leadId/convert'
      preLoaderRoute: typeof LeadsLeadIdConvertRouteImport
      parentRoute: typeof LeadsLeadIdRoute
    }
    '/clients/$clientId/edit': {
      id: '/clients/$clientId/edit'
      path: '/edit'
      fullPath: '/clients/$clientId/edit'
      preLoaderRoute: typeof ClientsClientIdEditRouteImport
      parentRoute: typeof ClientsClientIdRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClientsClientIdRouteChildren {
  ClientsClientIdEditRoute: typeof ClientsClientIdEditRoute
}

const ClientsClientIdRouteChildren: ClientsClientIdRouteChildren = {
  ClientsClientIdEditRoute: ClientsClientIdEditRoute,
}

const ClientsClientIdRouteWithChildren = ClientsClientIdRoute._addFileChildren(
  ClientsClientIdRouteChildren,
)

interface ClientsRouteChildren {
  ClientsClientIdRoute: typeof ClientsClientIdRouteWithChildren
  ClientsNewRoute: typeof ClientsNewRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsClientIdRoute: ClientsClientIdRouteWithChildren,
  ClientsNewRoute: ClientsNewRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface LeadsLeadIdRouteChildren {
  LeadsLeadIdConvertRoute: typeof LeadsLeadIdConvertRoute
  LeadsLeadIdEditRoute: typeof LeadsLeadIdEditRoute
}

const LeadsLeadIdRouteChildren: LeadsLeadIdRouteChildren = {
  LeadsLeadIdConvertRoute: LeadsLeadIdConvertRoute,
  LeadsLeadIdEditRoute: LeadsLeadIdEditRoute,
}

const LeadsLeadIdRouteWithChildren = LeadsLeadIdRoute._addFileChildren(
  LeadsLeadIdRouteChildren,
)

interface LeadsRouteChildren {
  LeadsLeadIdRoute: typeof LeadsLeadIdRouteWithChildren
  LeadsKanbanRoute: typeof LeadsKanbanRoute
  LeadsNewRoute: typeof LeadsNewRoute
}

const LeadsRouteChildren: LeadsRouteChildren = {
  LeadsLeadIdRoute: LeadsLeadIdRouteWithChildren,
  LeadsKanbanRoute: LeadsKanbanRoute,
  LeadsNewRoute: LeadsNewRoute,
}

const LeadsRouteWithChildren = LeadsRoute._addFileChildren(LeadsRouteChildren)

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdEditRoute: typeof ProjectsProjectIdEditRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdEditRoute: ProjectsProjectIdEditRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface TicketsTicketIdRouteChildren {
  TicketsTicketIdEditRoute: typeof TicketsTicketIdEditRoute
}

const TicketsTicketIdRouteChildren: TicketsTicketIdRouteChildren = {
  TicketsTicketIdEditRoute: TicketsTicketIdEditRoute,
}

const TicketsTicketIdRouteWithChildren = TicketsTicketIdRoute._addFileChildren(
  TicketsTicketIdRouteChildren,
)

interface TicketsRouteChildren {
  TicketsTicketIdRoute: typeof TicketsTicketIdRouteWithChildren
  TicketsKanbanRoute: typeof TicketsKanbanRoute
  TicketsNewRoute: typeof TicketsNewRoute
}

const TicketsRouteChildren: TicketsRouteChildren = {
  TicketsTicketIdRoute: TicketsTicketIdRouteWithChildren,
  TicketsKanbanRoute: TicketsKanbanRoute,
  TicketsNewRoute: TicketsNewRoute,
}

const TicketsRouteWithChildren =
  TicketsRoute._addFileChildren(TicketsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientsRoute: ClientsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DataRoute: DataRoute,
  LeadsRoute: LeadsRouteWithChildren,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SearchRoute: SearchRoute,
  TicketsRoute: TicketsRouteWithChildren,
  OnboardingLanguageRoute: OnboardingLanguageRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
